import { useEffect, useState } from "react"
import { createClient } from "@supabase/supabase-js"
import { Howl } from "howler"

const supabase = createClient(
  "https://YOUR_PROJECT.supabase.co",
  "YOUR_PUBLIC_ANON_KEY"
)

let sound = null

export default function Aura() {

  const [category,setCategory] = useState("void")
  const [playing,setPlaying] = useState(false)
  const [volume,setVolume] = useState(0.7)
  const [fade,setFade] = useState(false)

  const categories = {
    void:{
      name:"The Void (Insomnia)",
      video:"/videos/stars.mp4",
      audio:"/audio/sleep.mp3",
      color:"#20E2D7"
    },

    ground:{
      name:"The Ground (Trauma)",
      video:"/videos/forest.mp4",
      audio:"/audio/trauma.mp3",
      color:"#9D85FF"
    },

    breath:{
      name:"The Breath (Depletion)",
      video:"/videos/ocean.mp4",
      audio:"/audio/depletion.mp3",
      color:"#20E2D7"
    }
  }

  function loadAudio() {

    if(sound) sound.stop()

    sound = new Howl({
      src:[categories[category].audio],
      loop:true,
      volume:volume,
      html5:true
    })

  }

  function playSound(){

    if(!sound) loadAudio()

    sound.play()
    setPlaying(true)

    syncListening("playing")
  }

  function pauseSound(){

    if(sound) sound.pause()

    setPlaying(false)

    syncListening("paused")
  }

  function changeVolume(v){

    setVolume(v)

    if(sound) sound.volume(v)
  }

  async function syncListening(status){

    const user = (await supabase.auth.getUser()).data.user

    if(!user) return

    await supabase
    .from("CurrentlyListening")
    .upsert({
      user_id:user.id,
      preset_id:category,
      status:status,
      updated_at:new Date()
    })
  }

  function sleepTimer(minutes){

    setTimeout(()=>{

      if(sound){
        sound.fade(volume,0,6000)
      }

      setFade(true)

      setTimeout(()=>{

        if(sound) sound.stop()

        setPlaying(false)

      },6000)

    },minutes*60000)

  }

  useEffect(()=>{

    loadAudio()

  },[category])

  return (

  <div
  style={{
    background:"#0A0F14",
    color:"#E1E8ED",
    height:"100vh",
    overflow:"hidden",
    position:"relative"
  }}>

    {/* Live Photo Background */}

    <video
    src={categories[category].video}
    autoPlay
    loop
    muted
    style={{
      position:"absolute",
      width:"100%",
      height:"100%",
      objectFit:"cover",
      filter:"brightness(0.7)",
      opacity:fade?0:1,
      transition:"opacity 6s"
    }}
    />

    {/* Glass UI */}

    <div
    style={{
      position:"absolute",
      bottom:"40px",
      left:"50%",
      transform:"translateX(-50%)",
      backdropFilter:"blur(20px)",
      background:"rgba(255,255,255,0.08)",
      padding:"20px",
      borderRadius:"20px",
      display:"flex",
      gap:"15px"
    }}
    >

      <button onClick={playSound}
      style={{
        background:"#20E2D7",
        border:"none",
        padding:"12px",
        borderRadius:"50%"
      }}>
      ▶
      </button>

      <button onClick={pauseSound}
      style={{
        background:"#9D85FF",
        border:"none",
        padding:"12px",
        borderRadius:"50%"
      }}>
      ❚❚
      </button>

      <input
      type="range"
      min="0"
      max="1"
      step="0.01"
      value={volume}
      onChange={(e)=>changeVolume(e.target.value)}
      />

    </div>

    {/* Category Navigation */}

    <div
    style={{
      position:"absolute",
      top:"30px",
      left:"50%",
      transform:"translateX(-50%)",
      display:"flex",
      gap:"20px"
    }}>

      <button onClick={()=>setCategory("void")}>
      The Void
      </button>

      <button onClick={()=>setCategory("ground")}>
      The Ground
      </button>

      <button onClick={()=>setCategory("breath")}>
      The Breath
      </button>

    </div>

    {/* Sleep Timer */}

    <div
    style={{
      position:"absolute",
      right:"30px",
      bottom:"30px"
    }}>

      <button onClick={()=>sleepTimer(10)}>
      Sleep 10m
      </button>

    </div>

    {/* About */}

    <div
    style={{
      position:"absolute",
      left:"30px",
      bottom:"30px",
      fontSize:"12px"
    }}>

      <p>Aura: A Digital Sanctuary</p>
      <p>Developed & Generated by: Sedaprolan</p>
      <p>Creative Direction: Crom_ismyname</p>
      <p>Inquiries & Support: 0760580717</p>
      <p>Powered by Supabase</p>

    </div>

  </div>

  )
}